%kcknn_classify 'Classify an object using the K-Nearest Neighbors algorithm '
% This MatLab function was automatically generated by a converter (KhorosToMatLab) from the Khoros cknn_classify.pane file
%
% Parameters: 
% InputFile: iimage 'Input Image', required: 'input image file'
% InputFile: isigs 'Input Signatures', required: 'input signatures file'
% Integer: rank 'Use membership rank', default: 1: 'rank value for classification'
% OutputFile: oclass 'Output Classified', required: 'output classified image'
% OutputFile: oprob 'Output Probabilities', optional: 'output a posteriori probabilities'
% OutputFile: oinfo 'Output Information', optional: 'output information about classification'
% Integer: k 'K-Nearest Neighbors', default: 5: 'if set will use K-nearest neighbors'
%
% Example: [oclass, oprob, oinfo] = kcknn_classify({iimage, isigs}, {'iimage','';'isigs','';'rank',1;'oclass','';'oprob','';'oinfo','';'k',5})
%
% Khoros helpfile follows below:
%
%  PROGRAM
% cknn_classify - Classify an object using the K-Nearest Neighbors algorithm
%
%  DESCRIPTION
% This routine classifies an object using the K-Nearest Neighbors classification algorithm. The K-Nearest Neighbors classification algorith is a simple non-parametric algorithm that assigns a class C to a pixel X if the majority of the known neighbors of X is of class C. More details about the K-Nearest Neighbors classifier are on the Classify Toolbox Manual.
% Usually the normal K-Nearest Neighbors algorithm will be used, in this case the user must specify the value for K with the parameter [-k]. Another method that can be used is consider the neighborhood inside a hypersphere of radius R (specified with the [-R] parameter), in this case some pixels will be possible rejected if inside the hypersphere there aren't any points with known classes.
% This routine requires an input object to be classified (specified by the parameter [-iimage]) and a set of classes's signatures object created by "cknn_signature" and appended by \fIcsigappend\fP (specified by the parameter [-isigs]).
% This routine will create the output classification result in the file specified by [-oclass]. Optionally the final neighbor counts for each point and each class can be created if the parameter [-oprob] is used. If a file is specified in the parameter [-oinfo] the classification results will be written to that file in ASCII (can get large for large images).
% The expected dimensions of the input and output objects are shown below:
% The input object which will be classified will have dimensions WxHxDxTxF, where F is the number of features. If it has mask, the masked points won't be classified, and the corresponding points in the output will have value 0 and mask 0.
% The input signatures must have dimensions Nx2x1x1xF, where N is the total number of samples for all classes and F is the number of features in the signatures vector. It must be created by using "cknn_signature" and \fIcsigappend\fP.
% The output object (specified with the parameter [-oclass]) will have dimensions WxHxDxTx1, and its value segment will have values on the range 0..N, where 0 means that the pixel was rejected (see below). It will also have a corresponding mask segment with values 0 for the rejected pixels and 1 for the non-rejected pixels. The values for the pixels will be associated accordingly to the labels that were created with "csigappend".
% If the parameter [-oprob] is used, it will have dimensions WxHxDxTxN.
% Alternatively to the K-Nearest Neighbors classification, the second (or third, or N-th) most frequent class can be obtained by specifying an index in the [-rank] parameter.
% Please refer to the Classify toolbox manual or for one of the example workspaces for usage examples and details.
%
%  
%
%  EXAMPLES
% All examples for the Classify toolbox are listed on the Classify Toolbox Manual. For examples of this program, please see the Classify:workspaces:KNN and Classify:workspaces:KNN-Classify example workspaces.
%
%  "SEE ALSO"
% cknn_signature, csigappend.
%
%  RESTRICTIONS 
% Expects the signatures to be valid signatures for the K-Nearest Neighbors algorithm. This version of the algorithm does \fBnot" solve ties in the classification.
%
%  REFERENCES 
% All references for the Classify toolbox are listed on the Classify Toolbox Manual.
%
%  COPYRIGHT
% Copyright (C) 1997 Rafael Santos. Khoros (C) Khoral Research, Inc.
% 


function varargout = kcknn_classify(varargin)
if nargin ==0
  Inputs={};arglist={'',''};
elseif nargin ==1
  Inputs=varargin{1};arglist={'',''};
elseif nargin ==2
  Inputs=varargin{1}; arglist=varargin{2};
else error('Usage: [out1,..] = kcknn_classify(Inputs,arglist).');
end
if size(arglist,2)~=2
  error('arglist must be of form {''ParameterTag1'',value1;''ParameterTag2'',value2}')
 end
narglist={'iimage', '__input';'isigs', '__input';'rank', 1;'oclass', '__output';'oprob', '__output';'oinfo', '__output';'k', 5};
maxval={0,0,2,0,1,1,2};
minval={0,0,2,0,1,1,2};
istoggle=[0,0,1,0,1,1,1];
was_set=istoggle * 0;
paramtype={'InputFile','InputFile','Integer','OutputFile','OutputFile','OutputFile','Integer'};
% identify the input arrays and assign them to the arguments as stated by the user
if ~iscell(Inputs)
Inputs = {Inputs};
end
NumReqOutputs=1; nextinput=1; nextoutput=1;
  for ii=1:size(arglist,1)
  wasmatched=0;
  for jj=1:size(narglist,1)
   if strcmp(arglist{ii,1},narglist{jj,1})  % a given argument was matched to the possible arguments
     wasmatched = 1;
     was_set(jj) = 1;
     if strcmp(narglist{jj,2}, '__input')
      if (nextinput > length(Inputs)) 
        error(['Input ' narglist{jj,1} ' has no corresponding input!']); 
      end
      narglist{jj,2} = 'OK_in';
      nextinput = nextinput + 1;
     elseif strcmp(narglist{jj,2}, '__output')
      if (nextoutput > nargout) 
        error(['Output nr. ' narglist{jj,1} ' is not present in the assignment list of outputs !']); 
      end
      if (isempty(arglist{ii,2}))
        narglist{jj,2} = 'OK_out';
      else
        narglist{jj,2} = arglist{ii,2};
      end

      nextoutput = nextoutput + 1;
      if (minval{jj} == 0)  
         NumReqOutputs = NumReqOutputs - 1;
      end
     elseif isstr(arglist{ii,2})
      narglist{jj,2} = arglist{ii,2};
     else
        if strcmp(paramtype{jj}, 'Integer') & (round(arglist{ii,2}) ~= arglist{ii,2})
            error(['Argument ' arglist{ii,1} ' is of integer type but non-integer number ' arglist{ii,2} ' was supplied']);
        end
        if (minval{jj} ~= 0 | maxval{jj} ~= 0)
          if (minval{jj} == 1 & maxval{jj} == 1 & arglist{ii,2} < 0)
            error(['Argument ' arglist{ii,1} ' must be bigger or equal to zero!']);
          elseif (minval{jj} == -1 & maxval{jj} == -1 & arglist{ii,2} > 0)
            error(['Argument ' arglist{ii,1} ' must be smaller or equal to zero!']);
          elseif (minval{jj} == 2 & maxval{jj} == 2 & arglist{ii,2} <= 0)
            error(['Argument ' arglist{ii,1} ' must be bigger than zero!']);
          elseif (minval{jj} == -2 & maxval{jj} == -2 & arglist{ii,2} >= 0)
            error(['Argument ' arglist{ii,1} ' must be smaller than zero!']);
          elseif (minval{jj} ~= maxval{jj} & arglist{ii,2} < minval{jj})
            error(['Argument ' arglist{ii,1} ' must be bigger than ' num2str(minval{jj})]);
          elseif (minval{jj} ~= maxval{jj} & arglist{ii,2} > maxval{jj})
            error(['Argument ' arglist{ii,1} ' must be smaller than ' num2str(maxval{jj})]);
          end
        end
     end
     if ~strcmp(narglist{jj,2},'OK_out') &  ~strcmp(narglist{jj,2},'OK_in') 
       narglist{jj,2} = arglist{ii,2};
     end
   end
   end
   if (wasmatched == 0 & ~strcmp(arglist{ii,1},''))
        error(['Argument ' arglist{ii,1} ' is not a valid argument for this function']);
   end
end
% match the remaining inputs/outputs to the unused arguments and test for missing required inputs
 for jj=1:size(narglist,1)
     if  strcmp(paramtype{jj}, 'Toggle')
        if (narglist{jj,2} ==0)
          narglist{jj,1} = ''; 
        end;
        narglist{jj,2} = ''; 
     end;
     if  ~strcmp(narglist{jj,2},'__input') && ~strcmp(narglist{jj,2},'__output') && istoggle(jj) && ~ was_set(jj)
          narglist{jj,1} = ''; 
          narglist{jj,2} = ''; 
     end;
     if strcmp(narglist{jj,2}, '__input')
      if (minval{jj} == 0)  % meaning this input is required
        if (nextinput > size(Inputs)) 
           error(['Required input ' narglist{jj,1} ' has no corresponding input in the list!']); 
        else
          narglist{jj,2} = 'OK_in';
          nextinput = nextinput + 1;
        end
      else  % this is an optional input
        if (nextinput <= length(Inputs)) 
          narglist{jj,2} = 'OK_in';
          nextinput = nextinput + 1;
        else 
          narglist{jj,1} = '';
          narglist{jj,2} = '';
        end;
      end;
     else 
     if strcmp(narglist{jj,2}, '__output')
      if (minval{jj} == 0) % this is a required output
        if (nextoutput > nargout & nargout > 1) 
           error(['Required output ' narglist{jj,1} ' is not stated in the assignment list!']); 
        else
          narglist{jj,2} = 'OK_out';
          nextoutput = nextoutput + 1;
          NumReqOutputs = NumReqOutputs-1;
        end
      else % this is an optional output
        if (nargout - nextoutput >= NumReqOutputs) 
          narglist{jj,2} = 'OK_out';
          nextoutput = nextoutput + 1;
        else 
          narglist{jj,1} = '';
          narglist{jj,2} = '';
        end;
      end
     end
  end
end
if nargout
   varargout = cell(1,nargout);
else
  varargout = cell(1,1);
end
global KhorosRoot
if exist('KhorosRoot') && ~isempty(KhorosRoot)
w=['"' KhorosRoot];
else
if ispc
  w='"C:\Program Files\dip\khorosBin\';
else
[s,w] = system('which cantata');
w=['"' w(1:end-8)];
end
end
[varargout{:}]=callKhoros([w 'cknn_classify"  '],Inputs,narglist);
