%kg3daxis 'Generates a 3d axis geometry object from data.'
% This MatLab function was automatically generated by a converter (KhorosToMatLab) from the Khoros g3daxis.pane file
%
% Parameters: 
% InputFile: i 'Input 3D data', required: 'Data file containing 3d location data.'
% String: name 'Object name', default: '3D_axis': 'Name used as the internal object name.'
% OutputFile: o 'Output Geometry', required: 'Geometry object containing a 3d axis.'
% Double: xmin 'Xmin', default: 0: 'Minimum X coordinate for user-specified extents.'
% Double: xmax 'Xmax', default: 0: 'Maximum X coordinate for user-specified extents.'
% Double: ymin 'Ymin', default: 0: 'Minimum Y coordinate for user-specified extents.'
% Double: ymax 'Ymax', default: 0: 'Maximum Y coordinate for user-specified extents.'
% Double: zmin 'Zmin', default: 0: 'Minimum Z coordinate for user-specified extents.'
% Double: zmax 'Zmax', default: 0: 'Maximum Z coordinate for user-specified extents.'
% Integer: tdensity 'Tick/Text Density', default: 4: 'Indicates the number of tick marks/text along each axis.'
% String: sprintf_format 'Sprintf format ', default: '%g': 'Raw text formatting string used when labels are sprintf\'ed. NOTE: the user\'s input string is NOT checked for validity. The format string should be valid for floating point values, eg: %g, %6.4f, etc..'
%
% Example: o = kg3daxis(i, {'i','';'name','3D_axis';'o','';'xmin',0;'xmax',0;'ymin',0;'ymax',0;'zmin',0;'zmax',0;'tdensity',4;'sprintf_format','%g'})
%
% Khoros helpfile follows below:
%
%  PROGRAM
% g3daxis - Generates a 3d axis geometry object from data.
%
%  DESCRIPTION
% This routine generates geometry representing a 3D axis system.  The
% extent of the axis system can either be explicitly specified, or
% automatically calculated from an existing location data set.  The
% axis system may be given a collective name for identification purposes.
% Labels and tic marks can be optionally included.
%
%  
%
%  EXAMPLES
%
%  "SEE ALSO"
% gextents
%
%  RESTRICTIONS 
%
%  REFERENCES 
%
%  COPYRIGHT
% Copyright (C) 1996,1997 , The Regents of the University of California.  All rights reserved.
% 


function varargout = kg3daxis(varargin)
if nargin ==0
  Inputs={};arglist={'',''};
elseif nargin ==1
  Inputs=varargin{1};arglist={'',''};
elseif nargin ==2
  Inputs=varargin{1}; arglist=varargin{2};
else error('Usage: [out1,..] = kg3daxis(Inputs,arglist).');
end
if size(arglist,2)~=2
  error('arglist must be of form {''ParameterTag1'',value1;''ParameterTag2'',value2}')
 end
narglist={'i', '__input';'name', '3D_axis';'o', '__output';'xmin', 0;'xmax', 0;'ymin', 0;'ymax', 0;'zmin', 0;'zmax', 0;'tdensity', 4;'sprintf_format', '%g'};
maxval={0,0,0,100,100,100,100,100,100,1,0};
minval={0,0,0,-100,-100,-100,-100,-100,-100,1,0};
istoggle=[0,1,0,1,1,1,1,1,1,1,1];
was_set=istoggle * 0;
paramtype={'InputFile','String','OutputFile','Double','Double','Double','Double','Double','Double','Integer','String'};
% identify the input arrays and assign them to the arguments as stated by the user
if ~iscell(Inputs)
Inputs = {Inputs};
end
NumReqOutputs=1; nextinput=1; nextoutput=1;
  for ii=1:size(arglist,1)
  wasmatched=0;
  for jj=1:size(narglist,1)
   if strcmp(arglist{ii,1},narglist{jj,1})  % a given argument was matched to the possible arguments
     wasmatched = 1;
     was_set(jj) = 1;
     if strcmp(narglist{jj,2}, '__input')
      if (nextinput > length(Inputs)) 
        error(['Input ' narglist{jj,1} ' has no corresponding input!']); 
      end
      narglist{jj,2} = 'OK_in';
      nextinput = nextinput + 1;
     elseif strcmp(narglist{jj,2}, '__output')
      if (nextoutput > nargout) 
        error(['Output nr. ' narglist{jj,1} ' is not present in the assignment list of outputs !']); 
      end
      if (isempty(arglist{ii,2}))
        narglist{jj,2} = 'OK_out';
      else
        narglist{jj,2} = arglist{ii,2};
      end

      nextoutput = nextoutput + 1;
      if (minval{jj} == 0)  
         NumReqOutputs = NumReqOutputs - 1;
      end
     elseif isstr(arglist{ii,2})
      narglist{jj,2} = arglist{ii,2};
     else
        if strcmp(paramtype{jj}, 'Integer') & (round(arglist{ii,2}) ~= arglist{ii,2})
            error(['Argument ' arglist{ii,1} ' is of integer type but non-integer number ' arglist{ii,2} ' was supplied']);
        end
        if (minval{jj} ~= 0 | maxval{jj} ~= 0)
          if (minval{jj} == 1 & maxval{jj} == 1 & arglist{ii,2} < 0)
            error(['Argument ' arglist{ii,1} ' must be bigger or equal to zero!']);
          elseif (minval{jj} == -1 & maxval{jj} == -1 & arglist{ii,2} > 0)
            error(['Argument ' arglist{ii,1} ' must be smaller or equal to zero!']);
          elseif (minval{jj} == 2 & maxval{jj} == 2 & arglist{ii,2} <= 0)
            error(['Argument ' arglist{ii,1} ' must be bigger than zero!']);
          elseif (minval{jj} == -2 & maxval{jj} == -2 & arglist{ii,2} >= 0)
            error(['Argument ' arglist{ii,1} ' must be smaller than zero!']);
          elseif (minval{jj} ~= maxval{jj} & arglist{ii,2} < minval{jj})
            error(['Argument ' arglist{ii,1} ' must be bigger than ' num2str(minval{jj})]);
          elseif (minval{jj} ~= maxval{jj} & arglist{ii,2} > maxval{jj})
            error(['Argument ' arglist{ii,1} ' must be smaller than ' num2str(maxval{jj})]);
          end
        end
     end
     if ~strcmp(narglist{jj,2},'OK_out') &  ~strcmp(narglist{jj,2},'OK_in') 
       narglist{jj,2} = arglist{ii,2};
     end
   end
   end
   if (wasmatched == 0 & ~strcmp(arglist{ii,1},''))
        error(['Argument ' arglist{ii,1} ' is not a valid argument for this function']);
   end
end
% match the remaining inputs/outputs to the unused arguments and test for missing required inputs
 for jj=1:size(narglist,1)
     if  strcmp(paramtype{jj}, 'Toggle')
        if (narglist{jj,2} ==0)
          narglist{jj,1} = ''; 
        end;
        narglist{jj,2} = ''; 
     end;
     if  ~strcmp(narglist{jj,2},'__input') && ~strcmp(narglist{jj,2},'__output') && istoggle(jj) && ~ was_set(jj)
          narglist{jj,1} = ''; 
          narglist{jj,2} = ''; 
     end;
     if strcmp(narglist{jj,2}, '__input')
      if (minval{jj} == 0)  % meaning this input is required
        if (nextinput > size(Inputs)) 
           error(['Required input ' narglist{jj,1} ' has no corresponding input in the list!']); 
        else
          narglist{jj,2} = 'OK_in';
          nextinput = nextinput + 1;
        end
      else  % this is an optional input
        if (nextinput <= length(Inputs)) 
          narglist{jj,2} = 'OK_in';
          nextinput = nextinput + 1;
        else 
          narglist{jj,1} = '';
          narglist{jj,2} = '';
        end;
      end;
     else 
     if strcmp(narglist{jj,2}, '__output')
      if (minval{jj} == 0) % this is a required output
        if (nextoutput > nargout & nargout > 1) 
           error(['Required output ' narglist{jj,1} ' is not stated in the assignment list!']); 
        else
          narglist{jj,2} = 'OK_out';
          nextoutput = nextoutput + 1;
          NumReqOutputs = NumReqOutputs-1;
        end
      else % this is an optional output
        if (nargout - nextoutput >= NumReqOutputs) 
          narglist{jj,2} = 'OK_out';
          nextoutput = nextoutput + 1;
        else 
          narglist{jj,1} = '';
          narglist{jj,2} = '';
        end;
      end
     end
  end
end
if nargout
   varargout = cell(1,nargout);
else
  varargout = cell(1,1);
end
global KhorosRoot
if exist('KhorosRoot') && ~isempty(KhorosRoot)
w=['"' KhorosRoot];
else
if ispc
  w='"C:\Program Files\dip\khorosBin\';
else
[s,w] = system('which cantata');
w=['"' w(1:end-8)];
end
end
[varargout{:}]=callKhoros([w 'g3daxis"  '],Inputs,narglist);
